### PR TITLE
allow custom listener ip and port for the epmd daemon

### PR DESCRIPTION
**Pull request by silviucm**
Hi @halturin , great fork of the original library, thank you for maintaining it.

I am proposing adding a non-breaking change to that code allowing custom ports for the epmd daemon, in the eventuality of multiple separate node clusters (and thus, multiple epmd instances).

It uses optional arguments, and should not change anything if those are not specified. 

Regards,
silviu

### CODE REVIEW

**Comment by halturin** [comment]
Hi @silviucm ! Thanx! It's goog improvement! but I have different vision of this feature. I'm going to implement the ability to use 'ergonode' with embedded epmd feature, so the start options going to have some extra placeholders. Just as an example:
```
-epmd_mode       client|server (client - default)
-epmd_port       4369|port     (4369 - default)
-epmd_host       localhost|interface (localhost - default)
```

**Comment by silviucm** [comment]
That would be an amazing portability feature. An embedded daemon would allow deployments in "unfriendly" environments / restrictive containers, etc. 
Do you think you will have time to work on it this year ?

Feel free to close this pull request, but if you can accept a temporary stop gap measure,  I would definitely prefer working with your original package directly than maintain a fork of my own just for the custom port feature.

cheers

**Comment by halturin** [comment]
>Do you think you will have time to work on it this year ?
i'm gonna get it done this summer

>accept a temporary stop gap measure
give me couple days for the deep review of your pr.

**Comment by silviucm** [comment]
I agree with you that we should not impose unnecessary features on what is essentially an Erlang-based facilitator.

On the other hand, I think we should aspire to make the library available to as many developers as possible, including the ones less willing to debug why the communication "doesn't appear to be working with 'my phoenix app'. I won't use this". Some simply do not have time. 

Would you be ok, if I revert the pg2PubSub features, but place an additional paragraph in the README ? That paragraph would make a note for users of Elixir / Phonix and require them do define a minimal dedicated GenServer that would handle those pgPubSub signals, currently unhandled.

cheers

**Comment by halturin** [comment]
Done. take a look the latest changes, please
ps: sorry for delay :)

**Comment by silviucm** [comment]
wow - long time no see :)
I'll definitely test it when I make some time in the next few weeks - I'll let you know if I run into visible issues. I need to re-create the scenarios, since I haven't worked on this problem since last year either.
Cheers !

**Comment by halturin** [comment]
not valid anymore

**Pull request closed without merging**
